<a href="https://colab.research.google.com/github/hungzuj12345/Lab1_ML_17110037_HuynhNamThanhHung/blob/main/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Simple SVM


In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing

%matplotlib inline

irisdata = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/lung-cancer/lung-cancer.data")

irisdata.shape
irisdata.head()


le = preprocessing.LabelEncoder()
irisdata = irisdata.apply(le.fit_transform)
    
X = irisdata.drop('1', axis=1)
y = irisdata['1']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

y_pred = svclassifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[1 1 0]
 [2 0 0]
 [0 1 2]]
              precision    recall  f1-score   support

           0       0.33      0.50      0.40         2
           1       0.00      0.00      0.00         2
           2       1.00      0.67      0.80         3

    accuracy                           0.43         7
   macro avg       0.44      0.39      0.40         7
weighted avg       0.52      0.43      0.46         7

